version: '3.0'

services:

    elasitcsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
        container_name: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
            - "9300:9300"
        hostname: elasitcsearch
        volumes:
            - esdata:/usr/share/elasticsearch/data
        
        
volumes:
    esdata:
        driver: local